// <auto-generated/>

using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Animations.Rigging;

#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.SceneManagement;
#endif

namespace UnityEngine.Animations.Rigging.Saving
{
    public class TwistCorrectionSaver : MonoBehaviour
    {
        [SerializeField] private List<string> transformPathes = new List<string>(capacity:PropertyCount);
        [SerializeField] private TwistCorrection target;
        
        private const int PropertyCount = 1;
        [SerializeField] private int AllPropertyCount = PropertyCount;
    
        private void Awake()
        {
            var root = transform.root;
            if (!string.IsNullOrEmpty(transformPathes[0]))
                target.data.sourceObject = root.Find(transformPathes[0]);

            if (AllPropertyCount > PropertyCount)
            {
                for (int i = PropertyCount; i < AllPropertyCount; i++)
                    if(!string.IsNullOrEmpty(transformPathes[i])) 
                        target.data.twistNodes.SetTransform(i - PropertyCount, root.Find(transformPathes[i]));
            }
            
            Destroy(this);
        }
        
    #if UNITY_EDITOR
        private void OnValidate()
        {
            if(Application.isPlaying) return;
            if(target == null) return;
if(PrefabStageUtility.GetCurrentPrefabStage()!=null) return;
            //reset
            transformPathes.Clear();
            AllPropertyCount = PropertyCount;
            
            var trList = new[] {target.data.sourceObject};
            for (int i = 0; i < PropertyCount; i++)
            {
                if (trList[i])
                    transformPathes.Add(AnimationUtility.CalculateTransformPath(trList[i], transform.root));
                else
                    transformPathes.Add(string.Empty);
            }


            int sourcesLength = target.data.twistNodes.Count;
            if (sourcesLength > 0)
            {
                for (int i = 0; i < sourcesLength; i++)
                {
                    if (target.data.twistNodes[i].transform)
                        transformPathes.Add(AnimationUtility.CalculateTransformPath(target.data.twistNodes[i].transform, transform.root));
                    else
                        transformPathes.Add(string.Empty);
                }

                AllPropertyCount += sourcesLength;
            }
           
        }
    
        private void Reset() => OnValidate();
    
        [MenuItem("CONTEXT/TwistCorrection/Transfer motion to smth", false, 612)]
        public static void TransferMotionToConstraint(MenuCommand command)
        {
            var sourceScript = command.context as TwistCorrection;
            var thisScript = sourceScript.gameObject.AddComponent< TwistCorrectionSaver>();
            thisScript.target = sourceScript;
            thisScript.Reset();
        }
        
    #endif
        }
    }